### ISSUE TITLE
Add flint digging tool

### ISSUE THREAD

**Issue by SimonMeskens** [BTW-Community/De-Novo#13]
In order to find iron, the player might need to dig a bunch of stone, so we should add a flint digging tool crafted with either 2 flint, 1 string, 1 shaft, or 1 flint, 1 wicker, 1 shaft, 1 string.

It would be able to get through stone at an okay pace, and gravel piles would drop.

**Comment by socklessthing** [comment]
Closed with merge of branch feature/sickle
