### ISSUE TITLE
Composter doesn't reset icon correctly

### ISSUE THREAD

**Issue by SimonMeskens** [BTW-Community/De-Novo#23]
![image](https://github.com/user-attachments/assets/ed835280-0516-4062-bdc9-8043a590f715)

I don't know when it happens, but I filled a composter, waited until there were maggots, emptied it, got a dirt piles, and then when I next filled it, the texture was already maggots before filling.

**Comment by socklessthing** [comment]
Has other texture and model related problems. Need to fix
